from . import test_module_installation
from . import test_stock_location_admin
from . import test_stock_location_role
from . import test_stock_location_zone
from . import test_stock_location_zone_ui
from . import test_stock_location_storage_type
from . import test_stock_location_storage_type_ui
from . import test_wms_activity_area
from . import test_wms_activity_area_ui
from . import test_wms_storage_type
from . import test_wms_storage_type_ui
from . import test_wms_zone
from . import test_wms_zone_ui
