from . import test_module_installation
from . import test_wms_product_logistics
from . import test_operational_uom_roles
from . import test_tihi_configuration
from . import test_operational_classifications
from . import test_shelf_life_policy
from . import test_hu_type_restrictions
from . import test_quality_inspection_policy
from . import test_administrative_views
