[options]
; ==============================================================================
; Configuración General de Odoo para Entornos Contenedorizados (K3s / K8s / Docker)
; ==============================================================================
; Parámetros de base de datos se configuran dinámicamente mediante variables de entorno (HOST, PORT, USER, PASSWORD)
db_maxconn = 64

; Rutas de módulos (incluye los nativos y los addons personalizados de ERP/WMS/TMS)
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Almacenamiento de archivos y sesiones
data_dir = /var/lib/odoo

; Configuración de Red y Proxy
http_interface = 0.0.0.0
http_port = 8069
gevent_port = 8072
proxy_mode = True

; Multiprocesamiento: workers = 0 en desarrollo local permite que HTTP y WebSockets funcionen en el mismo puerto (8069) sin proxy inverso
workers = 0
max_cron_threads = 1

; Límites de memoria y tiempo
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 240
limit_time_real_cron = -1

; Logs (a la consola para captura por Docker/Kubernetes)
log_level = info
log_handler = [':INFO']
