apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  namespace: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/part-of: erp-wms-tms
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  rules:
    - host: odoo.local
      http:
        paths:
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: odoo-service
                port:
                  number: 8072
          - path: /longpolling
            pathType: Prefix
            backend:
              service:
                name: odoo-service
                port:
                  number: 8072
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-service
                port:
                  number: 8069
