apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
  namespace: odoo
type: Opaque
stringData:
  # Credenciales de Base de Datos PostgreSQL
  POSTGRES_USER: "odoo"
  POSTGRES_PASSWORD: "OdooDbSecurePassword2026!#"
  POSTGRES_DB: "odoo_production"
  
  # Clave Maestra de Odoo para administración de Bases de Datos
  ODOO_ADMIN_PASSWORD: "SuperMasterKeyOdoo2026!#"
